<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0;net5.0;netcoreapp3.1</TargetFrameworks>
    <Version>1.0.0</Version>
    <Authors>hfrances</Authors>
    <Company>TrCode</Company>
    <Product>qckdev.QuerySpecs.Abstractions</Product>
    <Description>Abstractions and collection contracts for qckdev QuerySpecs.</Description>
    <PackageProjectUrl>https://github.com/hfrances/qckdev.QuerySpecs</PackageProjectUrl>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
